### ISSUE TITLE
setup.sh very intrusive

### ISSUE THREAD

**Issue by Sciss** [martoo6/ScalaZen-IDE#18]
That script makes some wrong assumptions and dangerously interferes with the host system. It shouldn't even contain any `sudo`s.
- First of all, on Linux you don't necessarily have `JAVA_HOME`. So in my case, it would try to randomly install Java although it is already present. Note that `which java` will give you correct answer.
- You shouldn't infer from Linux to Debian and arbitrarily add apt sources to get sbt. A better solution would be to install Paul Phillips' script from https://github.com/paulp/sbt-extras . This can even be local without any permissions or the need to modify `PATH`.

**Comment by martoo6** [comment]
I agree, the installation it's really agressive. Will take a look at this as soon as I can.
