### ISSUE TITLE
Frontend beauty, robustness and correctnes

### ISSUE THREAD

**Issue by julianSelser** [martoo6/ScalaZen-IDE#19]
I'll address the following in batch, feel free to ask for more bullets in the comments as long as the complexity is low enough not to merit its own issue
- The **"new sketch" name input** in the modal **should have a placeholder and be styled** as a bootstrap input (or whatever looks right, and currently, it doesnt)
- New **sketches names should be validated to avoid special characters** otherwise it breaks the gallery, it's just a timebomb
- **If gallery is empty inform it** so we know the white screen doesn't mean it's broken
- The name of the sketch should show in the tag that says _MyApp_
- **Remove little plus sign beside the mentioned tag above** at least temporarily, we dont support tabs yet
- The first time either **when gallery and sketch are clicked, the intended animation doesnt trigger** so there's something going on there
- I should be able to press enter after filling the name for a new sketch and it should be created
- When the editor resizes to a single column due to lack of space, the page should look nice

**Comment by martoo6** [comment]
- In order to avoid special characters we could replace them with underscores.
- Feel free to change the animation library if it's easier for you.
